config/routes.rb
Rails.application.routes.draw do
  resources :lessons

  devise_for :users
  get 'pages/home'
  root 'pages#home'

end

app/models/lesson.rb
class Lesson < ActiveRecord::Base
	has_attached_file :picture, :styles => { :medium => "300x300>", :thumb => "100x100>" }, :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :picture, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

	def after_sign_in_path_for(resource)
  lessons_path
	end
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_lesson, only: [:show, :edit, :update, :destroy]

  # GET /lessons
  # GET /lessons.json
  def index
    @lessons = Lesson.all
  end

  # GET /lessons/1
  # GET /lessons/1.json
  def show
  end

  # GET /lessons/new
  def new
    @lesson = Lesson.new
  end

  # GET /lessons/1/edit
  def edit
  end

  # POST /lessons
  # POST /lessons.json
  def create
    @lesson = Lesson.new(lesson_params)

    respond_to do |format|
      if @lesson.save
        format.html { redirect_to @lesson, notice: 'Lesson was successfully created.' }
        format.json { render :show, status: :created, location: @lesson }
      else
        format.html { render :new }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /lessons/1
  # PATCH/PUT /lessons/1.json
  def update
    respond_to do |format|
      if @lesson.update(lesson_params)
        format.html { redirect_to @lesson, notice: 'Lesson was successfully updated.' }
        format.json { render :show, status: :ok, location: @lesson }
      else
        format.html { render :edit }
        format.json { render json: @lesson.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lessons/1
  # DELETE /lessons/1.json
  def destroy
    @lesson.destroy
    respond_to do |format|
      format.html { redirect_to lessons_url, notice: 'Lesson was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lesson
      @lesson = Lesson.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lesson_params
      params.require(:lesson).permit(:title, :author, :summary, :picture)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path, class: "navbar-brand" do %>
      SKYROCKET 
      <% end %>
          </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "HOME", lessons_path %></li>
        <% if user_signed_in? %> 
        <li><%= link_to new_lesson_path do %>
          <span class="glyphicon glyphicon-plus"></span> LESSON
          <% end %></li>
      <li><%= link_to "ACCOUNTS SETTINGS", edit_user_registration_path %></li>
      <li><%= link_to "LOG OUT", destroy_user_session_path, method: :delete %></li>
      <% else %> 
      <li><%= link_to "SIGN IN", new_user_session_path %></li>
      <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Skyrocket</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="main">

<%= render 'layouts/header' %>
<div class="container-fluid">
	<%= yield %>
	</div>

</body>
</html>

app/views/lessons/_form.html.erb
<%= form_for @lesson, html: { multipart: true } do |f| %>
  <% if @lesson.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lesson.errors.count, "error") %> prohibited this lesson from being saved:</h2>

      <ul>
      <% @lesson.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :author %><br>
    <%= f.text_field :author %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="field">
    <%= f.label :summary %><br>
    <%= f.text_area :summary %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/lessons/edit.html.erb
<h1>Editing Lesson</h1>

<%= render 'form' %>

<%= link_to 'Show', @lesson %> |
<%= link_to 'Back', lessons_path %>

app/views/lessons/index.html.erb
<h1 class="page-header">Web Development</h1>

<div class="row">
 <% @lessons.each do |lesson| %>
  <div class="lesson col-md-3">

    <h2> <%= link_to("#{lesson.title}", lesson) %></h2>
    <h3>by <%= lesson.author %></h3>
    <%= image_tag lesson.picture.url(:medium) %>
    <p><%= lesson.summary %></p>
    <%= link_to 'Show', lesson %>
    <%= link_to 'Edit', edit_lesson_path(lesson) %>
    <%= link_to 'Destroy', lesson, method: :delete, data: { confirm: 'Are you sure?' } %>

  </div> <!-- lesson -->
<% end %>
</div>

<h1 class="page-header">Photoshop</h1>

app/views/lessons/new.html.erb
<h1>New Lesson</h1>

<%= render 'form' %>

<%= link_to 'Back', lessons_path %>

app/views/lessons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @lesson.title %>
</p>

<p>
  <strong>Author:</strong>
  <%= @lesson.author %>
</p>

<p>
  <strong>Summary:</strong>
  <%= @lesson.summary %>
</p>

<%= link_to 'Edit', edit_lesson_path(@lesson) %> |
<%= link_to 'Back', lessons_path %>

app/views/pages/home.html.erb
<div class="container-fluid" id="home-1">
	<% flash.each do |name, msg| %>
	     <%= content_tag(:div, msg, class: "alert alert-#{name}") %>
	<% end %>
	<div class="row" id="home-1">
		<div class="home-container">
			<h1>You found the place for learning great stuffs</h1>
			<h2>Learn web development, make your own photoshop resume</h2>
			<%= link_to "Join Now", new_user_registration_path %>
		</div>
	</div>
</div>

<div class="container-fluid">
	<div class="row" id="footer">
		<div class="col-md-12 footer">
			<div class="col-md-6">Copyrigths Adrien Nhem. All rights reserved</div>
			<div class="col-md-6"></div>
		</div>
	</div>
</div>